### ISSUE TITLE
Railcraft Blast Furnace missing

### ISSUE THREAD

**Issue by wshadow** [andrewminer/crafting-guide#115]
I can't add a Railcraft Blast Furnace in the "Items you have" section. At least not by searching for "blast".

**Comment by andrewminer** [comment]
This should be corrected once [this card](https://trello.com/c/X3MbWv0S/54-create-a-sayt-item-picker) in Trello is corrected.

**Comment by andrewminer** [comment]
The newly launched item selector should eliminate this problem.
