### ISSUE TITLE
Add links from Forestry Wiki

### ISSUE THREAD

**Issue by andrewminer** [andrewminer/crafting-guide#117]
@CovertJaguar I have another request for you... I notice you're also deeply involved in Forestry.  Well, @sheldongriffin has recently added support for Forestry to CraftingGuide.   I'd also like to get links from the Forestry wiki page to Crafting Guide.  Are you the right person to talk to about that?

**Comment by andrewminer** [comment]
Any word on adding that link?  It would be much appreciated!

**Comment by CovertJaguar** [comment]
If I have an account, I don't remember what the login is. You are better off asking @mezz
