### ISSUE TITLE
Update Iron chests info

### ISSUE THREAD

**Issue by 61352151511** [andrewminer/crafting-guide#119]
Not sure if there's an "Updater" field but Iron Chests is being maintained by progwml6 and hasn't been touched by CPW in a long time. There are versions for 1.6.4, 1.7.10, and 1.8 that can be found here http://files.minecraftforge.net/IronChests2/

**Comment by andrewminer** [comment]
Thanks for that!  The only information I could find was at the official Minecraft forum, and that appeared to be rather old.  At the moment, I'm going to pass on adding support for older versions, as I suspect they're largely the same as the current version.
