### ISSUE TITLE
Add ExtraUtilities mod

### ISSUE THREAD

**Issue by TiuTalk** [andrewminer/crafting-guide#121]
Before anything, your website is awesome, @andrewminer  :)

I'm working to add **ExtraUtilities** support... I've already created the mod details & exported the images.. Now I need to define all the recipes.

There is no "easy" way of importing the recipes from NEI or something like that?

There are like 450 items on this mod :weary: 

see: https://trello.com/c/2OcIgdHS/47-extrautilities-14

**Comment by andrewminer** [comment]
Thanks!  It's been a lot of work, but well worth it!  Thanks for tackling ExtraUtilities... that is currently the most requested mod on the list, so it will make you quite the hero to get it in there.

Unfortunately, there really isn't a way to automate the recipe creation part.  You should already have a `mod-version.cg` file with the full item list from the NEI dump, but that's about all the automation I have currently.  One thing you can do to make things a *little* easier to to cut and paste the following after each item:
```yaml
    recipe:
        input: 
        pattern: 
        quantity: 1
        tools: Crafting Table
```

That will be correct most of the time, and it will save you having to enter it over and over.  One of these days, perhaps some enterprising mod author will figure out how to just dump all the recipes (or I'll learn enough modding to do it myself).

Let me know if you have any questions while working through things!

**Comment by TiuTalk** [comment]
That will help, indeed!

I've just removed all the decoration blocks (colored bricks & fancy glowstone blocks). This reduced the number of items to around 175~.

Is it OK to "publish" the mod with fewer items than it have? 

This way I can tackle the most important/required items now and then we add the decoration/less usefull blocks... I'm sure I can think of a script to automate that.

And what about the images? Ideally I should remove the images of the removed items, right?

**Comment by andrewminer** [comment]
With repetitive decoration blocks I've either just included all of them (e.g., [Mekanism](http://crafting-guide.com/browse/mekanism) or included just one example of the class while leaving the rest out (e.g., [BuildCraft Facades](http://crafting-guide.com/browse/buildcraft/facade_stone/).  These kind of blocks often have nearly identical recipes, so once you've finished the first one, it's mostly cut-n-paste with minor modifications.  I leave it up to you as to which makes the most sense.  Leave the extra images in any case... I may get around to adding the missing recipes if you decide to leave them out.

**Comment by TiuTalk** [comment]
So far, so good:

![](http://i.imgur.com/vFxZSCC.png)
