### ISSUE TITLE
Large numbers should be reduced (10000 -> 10k)

### ISSUE THREAD

**Issue by TiuTalk** [andrewminer/crafting-guide#123]
When working with numbers greater than 9999, the counts should converted to Ks or Ms.

Here you can't see how much cobblestone you need to craft the **12.960x compressed cobblestone** required to craft the **reinforced watering can**... It is around 116k cobblestone.

![Imgur](http://i.imgur.com/xfhS3sV.png)

**Comment by andrewminer** [comment]
Should be fixed now.  You still can't *enter* an amount larger than 9999, but it also shouldn't truncate the values either.
