### ISSUE TITLE
Simply Jetpacks: EnderIO versions

### ISSUE THREAD

**Issue by Gotolei** [andrewminer/crafting-guide#127]
Simply Jetpacks has a second line of jetpacks and fluxpacks made using EnderIO materials.

They come in roughly the same four tiers as the Thermal Expansion line, and there's a few extra EIO-specific items added as well.

**Comment by andrewminer** [comment]
Yeah, I noticed that when I was putting it together.  Unfortunately, Crafting Guide isn't smart enough (yet) to conditionally add recipes based upon whether or not another mod is available.  For now, I decided to stick with the Thermal Expansion recipes.  I've added [an issue](https://trello.com/c/tVULvfyX/13-some-recipes-are-sensitive-to-other-mods-3) in Trello for this.
