### ISSUE TITLE
Mekanism Metallurgic Infuser Recipes Always Operate in Batches of 10

### ISSUE THREAD

**Issue by misson20000** [andrewminer/crafting-guide#128]
When trying to craft a Digital Miner from Mekanism, Crafting Guide always tells me to make enriched alloys, reinforced alloys, atomic alloys etc. in batches of 10. If I'm trying to make a digital miner, I probably don't have the resources to spend 10 osmium making 10 enriched alloys when I only need 5 or however many I need

**Comment by andrewminer** [comment]
I know exactly what you're talking about, and I debated which way to go for some time.  It stems from the fact that Crafting Guide doesn't have the ability to require fractional amounts of something in a recipe combined with the use of things like Compressed Diamond in the Metallurgic Infuser.

For the Digital Miner, you need to combine some kind of diamond with Dirty Obsidian Dust to make Refined Obsidian Dust.  While you *can* use regular diamonds, you need 10x as many as if you use the Compressed Diamond.  So, the recipe has you go ahead and make the Compressed Diamond.

Of course, Compressed Diamond counts as 10 portions of "diamond" so far as the Metallurgic Infuser is concerned, so making 1 Refined Obsidian Dust really only need 1/10th of a Compressed Diamond.  Unfortunately, as I mentioned before, Crafting Guide currently can't handle fractional parts of ingredients, and so I decided to flip things around to make the recipe for 1 Compressed Diamond and 10 Dirty Obsidian Dust to produce 10 Enriched Obsidian Dust.

I've added [a card](https://trello.com/c/vEkEBGv5/133-allow-fractional-amounts-as-inputs) to Trello to add this feature.
