### ISSUE TITLE
Questions regarding the "Adding support for a new Mod" instructions

### ISSUE THREAD

**Issue by Whitellama** [andrewminer/crafting-guide#129]
I started off following the wiki instructions for adding support for a new mod, but I'm fairly sure of one of two things: either I'm missing a step, or the wiki is outdated. 

The first offender is the [Set up your environment](https://github.com/andrewminer/crafting-guide/wiki/Adding-support-for-a-new-Mod#2-set-up-your-environment) section. The wiki assumes the `grunt test` should work out of the box, but this was my experience:
* `$ cd crafting-guide-data`
* `$ grunt test`
  * [`Fatal error: Unable to find local grunt`](https://gist.githubusercontent.com/Whitellama/bf08f66433f85f03f728/raw/464c4a3433032eea81b88d29da57efff7539fc34/grunt%2520test)
* `$ npm install`
* `$ grunt test`
  * `Done, without errors.`

Is this an effect of my setup, or should the wiki instructions be changed?

Throughout the wiki the instructions say to put files in the `static` directory, but I've been having difficulty understanding its purpose. I attempted to follow the instructions to the letter, but it appears to me that nothing I put in the `static` folder actually gets used. I thought at first that maybe a script or grunt task will change that, but it doesn't appear so. Here's some examples of what it looks like after I followed the instructions:
* `crafting-guide-data/static/`
  * `browse/opencomputers/`
    * `icon.png`
    * `images/`
      * Why does `convert-nei-dump` put this here, but leave it empty?
    * The [Mod Data Format](https://github.com/andrewminer/crafting-guide/wiki/Mod-Data-Format) says this directory should contain "a directory for each item (named using the item's slug). Each directory should have a 48x48 icon.png file for that item. See Mod Version Data Format for details." The `convert-nei-dump` script creates such a thing, just in `crafting-guide-data/data/opencomputers/items/` instead of here. I copied it over, putting my faith in the wiki, but if this is correct the script should do it, shouldn't it?
  * `data/opencomputers/`
    * `mod.cg`
    * `TPPI2-1.5.3.455-dev/`
      * `mod-version.cg`

Also, `convert-nei-dump` generates a very bare-bones mod-version.cg in `crafting-guide-data/data/crafting-guide-data/data/`. If this file belongs in `crafting-guide-data/static/data/opencomputers/TPPI2-1.5.3.455-dev/', why doesn't it put it there?

The [Mod Version Data Format](https://github.com/andrewminer/crafting-guide/wiki/Mod-Version-Data-Format) then goes on to say "Each mod version directory should also contain an images subdirectory which contains an image file for each item described by the mod version. These images may be obtained as described in Adding Support for a New Mod." Well, the wiki said so, so I made the `images` folder. That's as far as I got, because the wording makes me think that the folder should contain .png files named after their items' slugs, like `images/grog.png`, but based on how the script set things up elsewhere in the repo, could it be like in `static/browse/opencomputers`, where it's `images/grog/icon.png`? The notion that we'd need the exact same files stored in multiple locations seems strange to me. Maybe I'm worrying too much. In any case, I left it empty, and ended up getting things to work. (You'll see how by scrolling down.)

The page also mentions `crafting-guide-data/scripts/verify`, which no longer appears to exist. I tried to find the commit which removed the file, to no avail. 

Finally ready to test, `grunt test` tells me `
 Error: ENOENT, no such file or directory './data/opencomputers/mod.cg'`. I replied with `cp ./static/data/opencomputers/mod.cg ./data/opencomputers/mod.cg`.

Another `grunt test` and ` Error: ENOENT, no such file or directory './data/opencomputers/icon.png'`, so I did `cp ./static/browse/opencomputers/icon.png ./data/opencomputers/icon.png`.

One more time, and `Error: missing "schema" declaratio`, so I said `cp static/data/opencomputers/TPPI2-1.5.3.455-dev/mod-version.cg data/opencomputers/versions/TPPI2-1.5.3.455-dev/mod-version.cg`.

The next test succeeded, hallelujah. I moved back into the crafting-guide repo, built, and ran the server, and stuff works! (Mostly, a few recipes are broken because I haven't finished mod-version.cg.)

Something's not right here, and I'm not very savvy with grunt (or any of this), so all I'm looking for is someone to chime in and tell me that either the wiki needs updating, I'm missing a step, or that I'm not insane. 

Yes, I am working on adding OpenComputers, but I'm starting with the version I play on which is 1.5.3.455-dev after lots of tweaking for the TPPI2 pack. I don't know what version of the pack. If I get it working, and get a better grip on this project, I'm more than happy to devote some time to adding a more updated and widely-used version of OpenComputers.

**Comment by Whitellama** [comment]
Oh, and assuming I'm right in thinking that the `static` folder can go out the window and that these files now just live in different places, I'm more than happy to edit the wiki to reflect this. Just need to know what's what before I can get the ball rolling.

**Comment by andrewminer** [comment]
Sorry you've been having problems!  I've fixed up a few problems in the instructions both about setting up your computer and with the placement of the various files.  You were correct that `static` is no longer correct.  Everything should wind up in the `data` directory, and you should have no `browse` directory in `crafting-guide-data` at all.

I'm not sure where you saw the reference to it, but the `verify` script has indeed been removed.  Just use `grunt test` instead.

Sounds like you figured out most of the errors (sorry!) and you're in good shape.  Feel free to create a pull request even if you're not completely done.  I'd be happy to take a look and help out with any confusions or errors you still see in there.

Also, Crafting Guide does support multiple versions of the same mod, so it's quite possible to support both the version you're working on now as well as the more popular one.

**Comment by andrewminer** [comment]
Also... thanks a lot for the detailed description of your challenges!  I think I've fixed all the documentation and scripts so that the next person doesn't have to go through the same problems.  :scream:

**Comment by Whitellama** [comment]
Looks like you got everything in the main page, but there were a few inaccuracies in the [Mod Data Format](https://github.com/andrewminer/crafting-guide/wiki/Mod-Data-Format) and [Mod Version Data Format](https://github.com/andrewminer/crafting-guide/wiki/Mod-Version-Data-Format) pages. That's where I saw the reference to the `verify` scripts, as well. I was hoping to open a PR, but apparentally GitHub wikis do not support that. In any case, I updated those two pages and pushed it to my fork, if you want to copy them over. I'm fairly sure I got everything. Here's some diffs of the changes I made:
* [Mod Data Format](https://github.com/Whitellama/crafting-guide/wiki/Mod-Data-Format/_compare/4eac47715b63b433d2103efb621305f2effd72b5...4c96f7a4ee3992e6cb10ce3644d1f60770edc787)
* [Mod Version Data Format](https://github.com/Whitellama/crafting-guide/wiki/Mod-Version-Data-Format/_compare/4786fbe3992eb21bde829be8678f8d13a97182d8...4c96f7a4ee3992e6cb10ce3644d1f60770edc787)

**Comment by Whitellama** [comment]
Oh, and about OpenComputers: What I'll probably end up doing is finishing the version I play on, then I'll add in the most recent version, and open a PR. Could be a few weeks depending on my schedule/motivation, but for now I'm actively working on it.

**Comment by andrewminer** [comment]
I've fixed up those pages as well in the "official" copy.  Thanks!

**Comment by Whitellama** [comment]
Awesome, thanks! I think that's everything, then.
