### ISSUE TITLE
Clicking "See Crafting Plan" from the Mekanism Jetpack page leads to instructions for an IC2 Jetpack instead

### ISSUE THREAD

**Issue by Whitellama** [andrewminer/crafting-guide#130]
It appears the See Crafting Plan button can point towards an item with the same name from a different mod. To reproduce:
1. Go to http://crafting-guide.com/browse/mekanism/jetpack/
2. Click See Crafting Plan
3. The crafting plan is for an IC2 jetpack, when it should be a Mekanism jetpack.

**Comment by Whitellama** [comment]
A potentially related issue is that the mod version data format doesn't allow one to differentiate between two items with the same name. For example, if I have a recipe with "Clay" in the input, it's ambiguous as to whether I'm referring to a piece of clay, or a clay block. Crafting Guide seems to assume a piece of clay, when really I want the latter. Perhaps there should be a way to (preferably optionally) specify the ID of input items to combat this?

**Comment by andrewminer** [comment]
Actually, it does, but that isn't documented anywhere.  You can use the full slug for the item in place of the item's name.  For example, for the Mekanism Jetpack, you'd used: "mekanism__jetpack"

**Comment by andrewminer** [comment]
Fixed in the current site.
