### ISSUE TITLE
Support for alternate recipes

### ISSUE THREAD

**Issue by pkmnfrk** [andrewminer/crafting-guide#131]
The FTB team recently unleashed the FTB Infinity Evolved pack on the world. This mod pack has all the usual tech mod suspects, but introduces the concept of different "modes". One of the modes is "expert mode". The idea behind expert mode is that they have rewritten many recipes to integrate the different mods together (as well as making things considerably more expensive). As an example, the basic "Flint & Steel" item in Minecraft now uses actual steel, wood crafts into 2 planks instead of 4, Buildcraft engines now use Forestry circuits, etc.

On the other hand, some recipes are exactly the same. Industrial-craft is 95% the same as it was before.

So, in order to support this, how about adding the concept of "alternate modes" or "alternate recipes". My idea is that you would pick your "mode" somewhere as a toggle, and the guide would preferentially pick the recipe for that mode, falling back to ordinary recipe if there isn't a special one.

The recipes themselves could be tagged with a mode, and the client could filter them based on the selected mode:

    item: Oak Wood Planks
        recipe:
            input: Oak Wood
            pattern: ... .0. ...
            quantity: 4

    item: Oak Wood Planks
        mode: expert
        recipe:
            input: Oak Wood
            pattern: ... .0. ...
            quantity: 2

**Comment by pkmnfrk** [comment]
So, I did some experimentation, and was able to add support for recipes like this:

    item: Oak Wood Planks
        recipe:
            input: Oak Wood
            pattern: ... .0. ...
            quantity: 4
        recipe: expert
            input: Oak Wood
            pattern: ... .0. ...
            quantity: 2

The crafting system will, if set to expert mode, first look for expert recipes and if none are found, look for normal recipes. A blank mode in the recipe, as above, implies normal. This allows for 100% backwards compatibility with the existing data files.

Branch: https://github.com/pkmnfrk/crafting-guide/tree/expert_mode

Things that are not done:

1. There is no UI, because I am the worst at front-end dev. We would probably want, at minimum, a means of picking your current mode, and probably warnings in places that not all recipes have been updated.
2. The current mode is stored directly in localStorage, and loaded into global.mode. I suspect the former might need some kind of encapsulation.
3. I have not written any new unit tests (though, I did ensure that I did not break the existing ones. Only a few minor tweaks were necessary to ensure this)
4. I have not added all of the new recipes. There are a lot of them, and I'm seriously considering writing a Minecraft mod that would allow automatic exporting of them. This would, of course, help with adding regular recipes too.

All that said, I'm not 100% sure the way I did it was the correct way. I will freely admit that I don't fully understand the way the crafting system works, and while I have not seen any regressions from this change, I feel like I might have done it in a way that goes against the design philosophy. Please feel free to offer suggestions and improvements.

**Comment by andrewminer** [comment]
@pkmnfrk — Thanks for giving this some thought!  As you suspected, there are a number of ways in which this doesn't quite fit with how things are implemented.  I tried to leave some specific comments, but it looks like I can't easily do that without a pull request.  If you could create one, I'll leave some specific comments to guide you moving forward.

**Comment by andrewminer** [comment]
@pkmnfrk — I'm going to close this issue for now, but if you'd like to submit a pull request with your suggested change, I'd be happy to consider it.
