### ISSUE TITLE
[putty; linux] convert-nei-dump error

### ISSUE THREAD

**Issue by lukiono** [andrewminer/crafting-guide#132]
When i try to run the script 'convert-nei-dump' this error shows up;

cg/crafting-guide-data/scripts/convert-nei-dump:45:28: error: missing '
        | tr '[A-Z]' '[a-z]' \

Command run;
coffee convert-nei-dump /opt/dumps/ BetterStorage 0.13.1.127

**Comment by andrewminer** [comment]
Thanks for reporting that, @lukiono.  I'll take a look when I'm able.  In the meantime, you might try removing the `\` on line 45 to see if that helps.  I use this script pretty often myself and haven't seen the problem you report, so it may have something to do with your shell or environment.

You can also try adding `-x` after the end of the first line.  That will give you more information about where the script it running into problems.

**Comment by lukiono** [comment]
Doesn't helped...
It points to ' but i replaced it already with ´ to test but doesn't work either.

**Comment by andrewminer** [comment]
@lukiono — I just noticed... did you try to run this using the `coffee` command on the command line?  That definitely won't work as this is a shell script.. not a CoffeeScript file.  Just get yourself into the `crafting-guide-data` directory and run: `./scripts/convert-nei-dump /opt/dumps BetterStorage 0.13.1.127`
