### ISSUE TITLE
Recipe for Molecular Assembler (Applied Energistics 2) has a mistake in it

### ISSUE THREAD

**Issue by Hense94** [andrewminer/crafting-guide#164]
http://crafting-guide.com/browse/applied_energistics_2/molecular_assembler/

As can be seen on http://ae-mod.info/Molecular-Assembler/ the actual recipe calls for two Quartz Glass NOT two Formation Cores.

**Comment by whizzball1** [comment]
https://github.com/andrewminer/crafting-guide-data/pull/11

That should be correct. It was a small error in the input. It'll be fixed once andrewminer merges.

**Comment by andrewminer** [comment]
Merged.
