### ISSUE TITLE
Can't set up the local server correctly (wiki/Adding Support for a New Mod)

### ISSUE THREAD

**Issue by whizzball1** [andrewminer/crafting-guide#165]
I can't quite find anywhere to put this, and I've gotten to the point where I can no longer proceed without setting up the local server, so I suppose I'll have to put my help request here--when running the commands you posted, I got up to "grunt clean build" before I got this error:

Running "rsync:static" (rsync) task
rsyncing ./static/ >>> ./dist/
Shell command was: rsync ./static/ ./dist/ --chmod=ugo=rwX --recursive
ERROR
Error: rsync exited with code 1
Warning: Task "rsync:static" failed.

I believe that I have installed rsync correctly, having updated the cmd file in the directory. I even put the folder into the crafting-guide repository, just to make sure. However, no matter what, I get that error. What do I do?

(Also, as an aside, I can't figure out how to "run the ./scripts/convert-nei-dump <path to .../dumps> <mod> <version> command", so help for that would be appreciated after this as well.)

**Comment by andrewminer** [comment]
What operating system are you running, Windows or something with a UNIX-like command line?

**Comment by whizzball1** [comment]
I am using Windows. I have already thoroughly scoured Google concerning the error and haven't really gotten anywhere--except that code 1 means invalid syntax.

**Comment by whizzball1** [comment]
The issue is now resolved. I used a Linux installation I have elsewhere to run the script that I needed--I can't really test my recipes, since almost every single one of them is in a format which doesn't work on the website yet.

**Comment by dragagon** [comment]
On my machine i manually run all the steps AFTER rsync in the main build script because windows did not want to play nice. I run rsync myself and it works, I run the build script and it hangs on that step. =\

**Comment by andrewminer** [comment]
@dragagon — Is that the case even when running under Cygwin or something similar?  All of these scripts were written in `bash`, and therefore should work on pretty much any UNIX shell.  It may be the case that the `rsync` you have installed is a Windows version rather than a version specific to your UNIX shell and is expecting `\` as a path delimiter rather than `/`.

**Comment by dragagon** [comment]
It's quite possible, it is the windows executable run in the git bash shell.
