### ISSUE TITLE
Windows - Unable to set up my environment to add support for a new mod (No such file or directory)

### ISSUE THREAD

**Issue by SoullessWaffle** [andrewminer/crafting-guide#215]
Every step outlined on [the wiki](https://github.com/andrewminer/crafting-guide/wiki/Adding-support-for-a-new-Mod) works fine without errors until the final step of part 2; "Set up your environment".

When I try to execute the command `./scripts/server`, I get this:
```
Waffles@DESKTOP-MH6IAHO /C/Users/Waffles/Documents/Projects/modding/minecraft/crafting-guide/crafting-guide (master) $ ./scripts/server
sh: ./scripts/server: No such file or directory
```

If I check the `./scripts` directory, I can see that there is indeed no `server` file there:
```
Waffles@DESKTOP-MH6IAHO /C/Users/Waffles/Documents/Projects/modding/minecraft/crafting-guide/crafting-guide (master) $ cd ./scripts && ls
deploy  publish  s3_upload  start  use_local_deps
```

**Comment by andrewminer** [comment]
Thanks for pointing that out!  I recently made some changes to the build system, and I clearly missed a spot updating the documentation.  You need to run `grunt clean start` at that place.  I've also updated the documentation.

**Comment by SoullessWaffle** [comment]
Glad to help, but unfortunately the issue does not seem to be resolved.
I'm getting a similar error when I run `grunt clean start`:
```
Waffles@DESKTOP-MH6IAHO /C/Users/Waffles/Documents/Projects/modding/minecraft/crafting-guide/crafting-guide (master) $ grunt clean start
Running "clean:assets" (clean) task
>> 1 path cleaned.

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "clean:templates" (clean) task
>> 1 path cleaned.

Running "jade:pages" (jade) task
>> 1 file created.

Running "jade:templates" (jade) task
>> 1 file created.

Running "copy:assets_build" (copy) task
Created 2 directories, copied 23 files

Running "copy:common_source" (copy) task
Copied 4 files

Running "copy:server_source" (copy) task
Copied 4 files

Running "sass_globbing:all" (sass_globbing) task

Running "sass:all" (sass) task

Running "browserify:external" task

Running "browserify:internal" task

Running "script:start" task
Fatal error: spawn .\scripts\start ENOENT
```

**Comment by andrewminer** [comment]
Are you running in the DOS shell, or in some kind of UNIX shell (e.g., [Cygwin](https://www.cygwin.com/))?  This build process is intended for a UNIX shell of some kind (e.g., MacOS X or Linux).

**Comment by andrewminer** [comment]
Also, can you verify that you do in fact have a `/scripts/start` script in your `crafting-guide` repository?

**Comment by SoullessWaffle** [comment]
I'm running these commands in [Git for Windows'](https://git-for-windows.github.io/) Git Bash (MINGW32). There does appear to be a file called `start` in the `/scripts` directory, these are the contents of that file:

```bash
#!/bin/bash

pushd './build/' &>/dev/null
clear
nodemon ./server.coffee $*
echo ''
popd &>/dev/null
```

If I `ls` in Git Bash, I can also see the file:
```
Waffles@DESKTOP-MH6IAHO /C/Users/Waffles/Documents/Projects/modding/minecraft/crafting-guide/crafting-guide (master) $ cd ./scripts && ls
deploy  publish  s3_upload  start  use_local_deps
```

**Comment by andrewminer** [comment]
Hmm.  Try adding `-x` to the end of the first line of the `start` script and run it directly from the root of your repository:

    > ./scripts/start

You should see it spew out each line it's going to execute as it does so.  The output might help us to understand where you're getting that error message from.  It's almost certainly something to do with being on a Windows machine which the GitHub shell doesn't entirely compensate for.  You might try downloading [Cygwin](https://www.cygwin.com/) and giving that a try instead.  It's  very old and reliable UNIX shell emulator for Windows.

**Comment by SoullessWaffle** [comment]
Interesting, running the script directly from Git Bash worked. The server booted and seems to be running fine. Looks like it's just Grunt that can't find the file for whatever reason.
