### ISSUE TITLE
Teleporting bug with Matter Transmitters/Receivers

### ISSUE THREAD

**Issue by LogicalEnigma** [andrewminer/crafting-guide#217]
Teleporting randomly causes this (Picture below) to happen. The odd part about it is that if I exit the world and reopen it, it renders the room as if I was standing there all along.
![2016-04-30_13 58 55](https://cloud.githubusercontent.com/assets/13333949/14937633/d411ab24-0edb-11e6-83f7-6eb75e5e1167.png) After teleporting, before leaving the world
![2016-04-30_14 01 53](https://cloud.githubusercontent.com/assets/13333949/14937644/353a098c-0edc-11e6-889a-289e128ba261.png) After restarting the world, My actual location

**Comment by andrewminer** [comment]
Sounds pretty weird, but I think you're in the wrong place.  This is the GitHub repository for http://crafting-guide.com.  I think you want to file this issue over in the [RFTools](https://github.com/McJty/RFTools) project.

**Comment by LogicalEnigma** [comment]
Thanks
