### ISSUE TITLE
Image interpolation doesn't work as expected on all platforms

### ISSUE THREAD

**Issue by MggMuggins** [andrewminer/crafting-guide#254]
As something that we have done to our wiki (see [http://lotrminecraftmod.wikia.com/wiki/The_Lord_of_the_Rings_Minecraft_Mod_Wiki](url) for the wiki), it has been really useful for easy texture use. Basically, the web automatically uses the some interpolation method (most likely cubic, although I really don't know for sure) to make zooming images look nicer. It works, for the most part. However, in the instance of crafting guide, the vast majority of your images are both tiny, and look better without blurring. So hence, I suggest setting the interpolation method on the site to None, that way, both the zoomed item previews are not blurred, but also so that the main icon is clear, and so that more flexibility could be added for image size. The update would make the site much cleaner and more professional looking.

EDIT: See our [http://lotrminecraftmod.wikia.com/wiki/MediaWiki:Common.css](url) for the CSS code on how we did this. I'm not sure whether or not the code would be directly applicable to crafting guide, but if it is, go ahead and use it. The license on the wiki allows merciless editing and copying. Also I know the guy who wrote the code...

**Comment by MggMuggins** [comment]
It'll be an Opera Issue then. I'm running Ubuntu 15.10 Wily Werewolf, and Opera 37.0. I'll show you the image, you just didn't add support for the interpolation method for Opera, which is understandable. The only reason my wiki has it is because the guy who wrote the code knew I used Opera and added that line. 
![opera interpolation difficulties](https://cloud.githubusercontent.com/assets/16041213/15786645/6aceb9be-2983-11e6-9459-336055fc1a91.png)

**Comment by andrewminer** [comment]
The image as you show it is what I would expect to see, with each pixel clearly distinct instead of being blurred and distorted.  For the original Minecraft art, it's more extreme than with some of the higher-res textures from certain mods (e.g., Galacticraft), but that does look as expected (and, I might add, what I see on the LOTR wiki).

**Comment by MggMuggins** [comment]
Try downloading the full-size image there and see what you see. I agree it's hard to see the problematic scaling from that shot in the resolution it is, but the interpolation method is incorrect in Opera.
~Samwise

**Comment by andrewminer** [comment]
I guess I'm not clear on what you're expecting to see.  Can you paste in an image which looks like what you're expecting?

**Comment by MggMuggins** [comment]
I've got one that my browser has zoomed and the actual source file from the wiki here:
![apple no-interpolation](https://cloud.githubusercontent.com/assets/16041213/15829708/84434a5a-2bda-11e6-8a69-383bcd132ab6.png)
![apple 16](https://cloud.githubusercontent.com/assets/16041213/15829712/8b2d95c8-2bda-11e6-81f4-4ed07140b5ae.png)
~Samwise
