### ISSUE TITLE
'Log in with github' requests unnecessary write access

### ISSUE THREAD

**Issue by kolen** [andrewminer/crafting-guide#279]
Write access is unnecessary when using github only as authentication service:

![image](https://cloud.githubusercontent.com/assets/24191/25569093/b69c010e-2e18-11e7-8d75-e22e0d03ff69.png)

**Comment by andrewminer** [comment]
Actually, Crafting Guide uses GitHub as much more than an authentication service.  When users edit wiki pages, their changes are saved as commits to the related documents in the [crafting-guide-data](https://github.com/andrewminer/crafting-guide-data) repository.  To add grant wiki editors contributor status (a necessary precondition to submitting a commit), Crafting Guide has to ask for this permission.  Be assured, though... it only ever requests data related to its own operation!

**Comment by Gunni** [comment]
Never going to happen:

This application will be able to read **and write** all public repository data. This includes the following:
- Code
- Issues
- Pull requests
- Wikis
- Settings
- Webhooks and services
- Deploy keys

You are dreaming, make a seperate auth section for that if you want that kind of access.
