### ISSUE TITLE
Skipper overspawning causing massive lag

### ISSUE THREAD

**Issue by mobro09** [andrewminer/crafting-guide#282]
Hi,

I found a huge swamp biome in my world, and skippers spawn to the point I am reduced to 1fps.
Using Opis I can kill all and the frame rate returns to normal but within a minute it's back to 1fps and around 250-400 entities.

Any possible way to fix this?

**Comment by andrewminer** [comment]
I'm afraid I have no idea what you're talking about.  I'd have to guess that you submitted this issue to the wrong repo.  :-(
