### ISSUE TITLE
Nodemon crashes

### ISSUE THREAD

**Issue by Dysproh** [andrewminer/crafting-guide#298]
Upon trying to start the server on localhost:8080, I get the following error:
![nodemoncrash](https://user-images.githubusercontent.com/25161213/29253726-24151b1a-804b-11e7-8991-b55d2b6dcae1.png)
I am using Ubuntu

By the way, the text is highlighted, I am using the built-in terminal app.
EDIT: Fixed by running 
    grunt clean build start

**Comment by andrewminer** [comment]
Glad you worked it out!  Feel free to open other issues if you run into problems.  I should warn you that I've recently launched a pretty substantial change to how the website works, and I haven't quite gotten around to updating all the documentation yet, so please do let me know if you run into other things which need fixing!
