### ISSUE TITLE
using crafting guide exporter to upload to crafting guide for crafting plans

### ISSUE THREAD

**Issue by coehlrich** [andrewminer/crafting-guide#302]
for this you might want to change it to use nei or jei for the machines not in crafting guide and you could group together the recipes by machines in the dump for crafting guide exporter.

**Comment by andrewminer** [comment]
Yup, that's the plan!

**Comment by coehlrich** [comment]
when will it be ready because i really want to use with project ozone 2 kappa mode.

**Comment by andrewminer** [comment]
Unfortunately, I can't really say... it's very much a side-project for me, and not one which on the "front burner" so to speak.  Also, Crafting Guide Exporter is my very first effort at mod making, so it's a pretty slow process for me.  I'm happy to accept pull requests, though!

**Comment by coehlrich** [comment]
i have made one full mod here https://github.com/coehlrich/chunk-logger
