### ISSUE TITLE
scripts/start not finding dists/index.js

### ISSUE THREAD

**Issue by coehlrich** [andrewminer/crafting-guide#303]
when i tried running `grunt clean build start` it says spawn .\scripts\start ENOENT and messing around to get it to run start it says dist/index.js is missing.

**Comment by andrewminer** [comment]
The scripts are intended for a UNIX-based system (like Linux or MacOS).  If you want to run on Windows, you have a few options.  If you're on Windows 10, Microsoft has actually released a [Linux Subsystem](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) which will work for you.  Other options include using [GitHub's own application](https://desktop.github.com), or grabbing the [Docker for Windows](https://docs.docker.com/docker-for-windows/)

**Comment by coehlrich** [comment]
how would i be able to do it on github desktop?

**Comment by coehlrich** [comment]
i did using windows subsystem for linux and it went much better but now in chrome it is stuck at the loading screen

**Comment by coehlrich** [comment]
i have got it running now i had to download the crafting-guide-common repository and build that and use that instead of the one in npm module and also copy the data folder from crafting-guide-data into the build/static folder.
