### ISSUE TITLE
Possible typo in README.md

### ISSUE THREAD

**Issue by tommylenz** [andrewminer/crafting-guide#319]
Hey @andrewminer! Just saw your Crafting Guide for the first time, and I have to say that's great work! When I read trough the readme, I was wondering whether this sentence is correct or not:

> From the your first crafting table ...

Shouldn't it be either
> From the first crafting table ...

or
> From your first crafting table ...

?

I'm from Germany and hence not native speaking, if it's correct then I am sorry for the inconvenience.
Once again, great work, I like it very much and it helped me a lot already!

Thomas

**Comment by andrewminer** [comment]
Hello @tommylenz!  Your English teacher should be proud, because you're quite correct.  I intended to say "From your first crafting table...".  Thanks for pointing that out!
