### ISSUE TITLE
Add support for Galacticraft

### ISSUE THREAD

**Issue by andrewminer** [andrewminer/crafting-guide#64]
URL: http://micdoodle8.com/mods/galacticraft

**Comment by lukiono** [comment]
i have this mod in my private pack. after im done with Harvestcraft im going for this.

**Comment by andrewminer** [comment]
Feel free!  If you'd like a (rough) view of which mods are mostly highly requested, check out [this list](https://github.com/andrewminer/crafting-guide/issues?q=is%3Aopen+label%3Amod+sort%3Acomments-desc).
